name: gtkx-example
base: core24
version: "0.1.0"
summary: GTKX Example Application
description: |
  An example application built with GTKX, demonstrating how to package
  React-based GTK4 applications for distribution on Linux.

grade: devel
confinement: strict

platforms:
  amd64:

parts:
  gtkx-example:
    plugin: nil
    source: .
    build-snaps:
      - node/22/stable
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp dist/app $CRAFT_PART_INSTALL/bin/gtkx-example
      cp dist/index.node $CRAFT_PART_INSTALL/bin/
      cp assets/icon.png $CRAFT_PART_INSTALL/meta/gui/
      cp snap/gtkx-example.desktop $CRAFT_PART_INSTALL/meta/gui/
    prime:
      - bin/gtkx-example
      - bin/index.node
      - meta/gui/

apps:
  gtkx-example:
    command: bin/gtkx-example
    desktop: meta/gui/gtkx-example.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
