name: gtkx-example
base: core24
version: "0.1.0"
summary: GTKX Example Application
description: |
  An example application built with GTKX, demonstrating how to package
  React-based GTK4 applications for distribution on Linux.

grade: devel
confinement: strict

platforms:
  amd64:

parts:
  gtkx-example:
    plugin: nil
    source: .
    build-snaps:
      - node/22/stable
    override-build: |
      node --experimental-sea-config sea-config.json
      cp /snap/node/current/bin/node app
      node vendor/postject.cjs app NODE_SEA_BLOB dist/sea-prep.blob --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2
      mkdir -p $CRAFT_PART_INSTALL/bin
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      mkdir -p $CRAFT_PART_INSTALL/share/gtkx-example
      cp app $CRAFT_PART_INSTALL/bin/gtkx-example
      cp dist/gtkx.node $CRAFT_PART_INSTALL/bin/
      if [ -d dist/assets ]; then cp -r dist/assets/* $CRAFT_PART_INSTALL/share/gtkx-example/; fi
      cp assets/icon.png $CRAFT_PART_INSTALL/meta/gui/
      cp snap/gtkx-example.desktop $CRAFT_PART_INSTALL/meta/gui/
    prime:
      - bin/gtkx-example
      - bin/gtkx.node
      - share/gtkx-example/
      - meta/gui/

apps:
  gtkx-example:
    command: bin/gtkx-example
    desktop: meta/gui/gtkx-example.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
