import { css } from "@gtkx/css";
import * as Gtk from "@gtkx/ffi/gtk";
import { GtkBox, GtkButton, GtkFlowBox, GtkScrolledWindow } from "@gtkx/react";
import type { Demo } from "../types.js";
import sourceCode from "./flowbox.tsx?raw";

const COLORS: { name: string; hex: string }[] = [
    { name: "Snow", hex: "#fffafa" },
    { name: "Ghost White", hex: "#f8f8ff" },
    { name: "White Smoke", hex: "#f5f5f5" },
    { name: "Gainsboro", hex: "#dcdcdc" },
    { name: "Floral White", hex: "#fffaf0" },
    { name: "Old Lace", hex: "#fdf5e6" },
    { name: "Linen", hex: "#faf0e6" },
    { name: "Antique White", hex: "#faebd7" },
    { name: "Papaya Whip", hex: "#ffefd5" },
    { name: "Blanched Almond", hex: "#ffebcd" },
    { name: "Bisque", hex: "#ffe4c4" },
    { name: "Peach Puff", hex: "#ffdab9" },
    { name: "Navajo White", hex: "#ffdead" },
    { name: "Moccasin", hex: "#ffe4b5" },
    { name: "Cornsilk", hex: "#fff8dc" },
    { name: "Ivory", hex: "#fffff0" },
    { name: "Lemon Chiffon", hex: "#fffacd" },
    { name: "Seashell", hex: "#fff5ee" },
    { name: "Honeydew", hex: "#f0fff0" },
    { name: "Mint Cream", hex: "#f5fffa" },
    { name: "Azure", hex: "#f0ffff" },
    { name: "Alice Blue", hex: "#f0f8ff" },
    { name: "Lavender", hex: "#e6e6fa" },
    { name: "Lavender Blush", hex: "#fff0f5" },
    { name: "Misty Rose", hex: "#ffe4e1" },
    { name: "White", hex: "#ffffff" },
    { name: "Black", hex: "#000000" },
    { name: "Dark Slate Gray", hex: "#2f4f4f" },
    { name: "Dim Gray", hex: "#696969" },
    { name: "Slate Gray", hex: "#708090" },
    { name: "Light Slate Gray", hex: "#778899" },
    { name: "Gray", hex: "#bebebe" },
    { name: "Light Gray", hex: "#d3d3d3" },
    { name: "Midnight Blue", hex: "#191970" },
    { name: "Navy", hex: "#000080" },
    { name: "Cornflower Blue", hex: "#6495ed" },
    { name: "Dark Slate Blue", hex: "#483d8b" },
    { name: "Slate Blue", hex: "#6a5acd" },
    { name: "Medium Slate Blue", hex: "#7b68ee" },
    { name: "Light Slate Blue", hex: "#8470ff" },
    { name: "Medium Blue", hex: "#0000cd" },
    { name: "Royal Blue", hex: "#4169e1" },
    { name: "Blue", hex: "#0000ff" },
    { name: "Dodger Blue", hex: "#1e90ff" },
    { name: "Deep Sky Blue", hex: "#00bfff" },
    { name: "Sky Blue", hex: "#87ceeb" },
    { name: "Light Sky Blue", hex: "#87cefa" },
    { name: "Steel Blue", hex: "#4682b4" },
    { name: "Light Steel Blue", hex: "#b0c4de" },
    { name: "Light Blue", hex: "#add8e6" },
    { name: "Powder Blue", hex: "#b0e0e6" },
    { name: "Pale Turquoise", hex: "#afeeee" },
    { name: "Dark Turquoise", hex: "#00ced1" },
    { name: "Medium Turquoise", hex: "#48d1cc" },
    { name: "Turquoise", hex: "#40e0d0" },
    { name: "Cyan", hex: "#00ffff" },
    { name: "Light Cyan", hex: "#e0ffff" },
    { name: "Cadet Blue", hex: "#5f9ea0" },
    { name: "Medium Aquamarine", hex: "#66cdaa" },
    { name: "Aquamarine", hex: "#7fffd4" },
    { name: "Dark Green", hex: "#006400" },
    { name: "Dark Olive Green", hex: "#556b2f" },
    { name: "Dark Sea Green", hex: "#8fbc8f" },
    { name: "Sea Green", hex: "#2e8b57" },
    { name: "Medium Sea Green", hex: "#3cb371" },
    { name: "Light Sea Green", hex: "#20b2aa" },
    { name: "Pale Green", hex: "#98fb98" },
    { name: "Spring Green", hex: "#00ff7f" },
    { name: "Lawn Green", hex: "#7cfc00" },
    { name: "Green", hex: "#00ff00" },
    { name: "Chartreuse", hex: "#7fff00" },
    { name: "Medium Spring Green", hex: "#00fa9a" },
    { name: "Green Yellow", hex: "#adff2f" },
    { name: "Lime Green", hex: "#32cd32" },
    { name: "Yellow Green", hex: "#9acd32" },
    { name: "Forest Green", hex: "#228b22" },
    { name: "Olive Drab", hex: "#6b8e23" },
    { name: "Dark Khaki", hex: "#bdb76b" },
    { name: "Khaki", hex: "#f0e68c" },
    { name: "Pale Goldenrod", hex: "#eee8aa" },
    { name: "Light Goldenrod Yellow", hex: "#fafad2" },
    { name: "Light Goldenrod", hex: "#eedd82" },
    { name: "Light Yellow", hex: "#ffffe0" },
    { name: "Yellow", hex: "#ffff00" },
    { name: "Gold", hex: "#ffd700" },
    { name: "Goldenrod", hex: "#daa520" },
    { name: "Dark Goldenrod", hex: "#b8860b" },
    { name: "Rosy Brown", hex: "#bc8f8f" },
    { name: "Indian Red", hex: "#cd5c5c" },
    { name: "Saddle Brown", hex: "#8b4513" },
    { name: "Sienna", hex: "#a0522d" },
    { name: "Peru", hex: "#cd853f" },
    { name: "Burlywood", hex: "#deb887" },
    { name: "Beige", hex: "#f5f5dc" },
    { name: "Wheat", hex: "#f5deb3" },
    { name: "Sandy Brown", hex: "#f4a460" },
    { name: "Tan", hex: "#d2b48c" },
    { name: "Chocolate", hex: "#d2691e" },
    { name: "Firebrick", hex: "#b22222" },
    { name: "Brown", hex: "#a52a2a" },
    { name: "Dark Salmon", hex: "#e9967a" },
    { name: "Salmon", hex: "#fa8072" },
    { name: "Light Salmon", hex: "#ffa07a" },
    { name: "Orange", hex: "#ffa500" },
    { name: "Dark Orange", hex: "#ff8c00" },
    { name: "Coral", hex: "#ff7f50" },
    { name: "Light Coral", hex: "#f08080" },
    { name: "Tomato", hex: "#ff6347" },
    { name: "Orange Red", hex: "#ff4500" },
    { name: "Red", hex: "#ff0000" },
    { name: "Hot Pink", hex: "#ff69b4" },
    { name: "Deep Pink", hex: "#ff1493" },
    { name: "Pink", hex: "#ffc0cb" },
    { name: "Light Pink", hex: "#ffb6c1" },
    { name: "Pale Violet Red", hex: "#db7093" },
    { name: "Maroon", hex: "#b03060" },
    { name: "Medium Violet Red", hex: "#c71585" },
    { name: "Violet Red", hex: "#d02090" },
    { name: "Magenta", hex: "#ff00ff" },
    { name: "Violet", hex: "#ee82ee" },
    { name: "Plum", hex: "#dda0dd" },
    { name: "Orchid", hex: "#da70d6" },
    { name: "Medium Orchid", hex: "#ba55d3" },
    { name: "Dark Orchid", hex: "#9932cc" },
    { name: "Dark Violet", hex: "#9400d3" },
    { name: "Blue Violet", hex: "#8a2be2" },
    { name: "Purple", hex: "#a020f0" },
    { name: "Medium Purple", hex: "#9370db" },
    { name: "Thistle", hex: "#d8bfd8" },
    { name: "Dark Gray", hex: "#a9a9a9" },
    { name: "Dark Blue", hex: "#00008b" },
    { name: "Dark Cyan", hex: "#008b8b" },
    { name: "Dark Magenta", hex: "#8b008b" },
    { name: "Dark Red", hex: "#8b0000" },
    { name: "Light Green", hex: "#90ee90" },
];

const colorStyles = COLORS.map(
    (color) => css`
        & {
            background-color: ${color.hex};
        }
    `,
);

const FlowBoxDemo = () => {
    return (
        <GtkScrolledWindow hscrollbarPolicy={Gtk.PolicyType.NEVER}>
            <GtkFlowBox maxChildrenPerLine={30} selectionMode={Gtk.SelectionMode.NONE} valign={Gtk.Align.START}>
                {COLORS.map((color, index) => (
                    <GtkButton key={color.name} tooltipText={`${color.name}\n${color.hex}`}>
                        <GtkBox widthRequest={24} heightRequest={24} cssClasses={[colorStyles[index] ?? ""]} />
                    </GtkButton>
                ))}
            </GtkFlowBox>
        </GtkScrolledWindow>
    );
};

export const flowboxDemo: Demo = {
    id: "flowbox",
    title: "Flow Box",
    description:
        "GtkFlowBox allows flexible and responsive grids which reflow as needed and support sorting and filtering. The children of a GtkFlowBox are regular widgets.",
    keywords: ["flowbox", "GtkFlowBox", "grid", "wrap", "responsive"],
    component: FlowBoxDemo,
    sourceCode,
};
